module.exports.message = {
    DATA_EMPTY: 'Hãy cung cấp đầy đủ dữ liệu',
    REGISTER_TURN: "Đăng kí thành công",
    SUBJECT_EMPTY: "Hãy chọn 1 môn học",
    WRONG_LOGIN: "Tài khoản hoặc mật khẩu sai",
    ERROR: 'Chúng tôi đã gặp sự cố!',
    PERMISSION: 'Bạn không có quyền để làm việc này',
    NOT_SUPER_ADMIN: "Tài khoản không phải là quản trị viên cao cấp",
    USER_EXIST: 'Người dùng đã tồn tại',
    CHANGE: 'Thay đổi thành công',
    ADDSUCCESS: 'Thêm thành công',
    DELETESUCCESS: 'Xoá thành công',
    EDITSUCCESS: 'Sửa thành công',
    NOT_ADMIN: "Chỉ quản trị viên mới có quyền",
    PARAM_MISSED: "Lỗi, hãy đăng nhập lại!",
    EXAM_EMPTY: "Hãy chọn 1 kì thi",
    TURNID_MISSED: "Hãy chọn 1 ca thi",
    REGISTER_TURN_FAILED: "Bạn không đủ điều kiện thi",
    DELETE_SUCCESS: "Xoá thành công",
    DUPLICATED_DATA: 'Dữ liệu nhập vào đã tồn tại',
    DISABLE_TEST: "Bạn không thể đăng kí thi môn này",
    REGIST_DUPPLICATE: "Bạn đã đăng kí thi môn này",
    SERVER_ERROR: "Server đang gặp sự cố",
    PASSWORD_CONFIRM_WRONG: "Password confirm không chính xác",
    PASSWORD_WRONG: 'Mật khẩu không chính xác',
    EXAM_EXISTED: "Kì thi này đã tồn tại",
    SUBJECT_NONE_EXISTED: 'Môn học không tồn tại',
    TURN_NONE_EXISTED: 'Ca thi không tồn tại',
    ROOM_NONE_EXISTED: 'Phòng thi không tồn tại',
    DATA_INPUT_INVALID: 'Dữ liệu thêm vào không hợp lệ',
    EMAIL_INVALID: 'Email không hợp lệ',
    DATA_USER_WRONG: 'Dữ liệu vào cần đầy đủ 3 cột theo thứ tự: mssv(kí tự), email, password',
    DATA_STUDENT_SUBJECT_WRONG: 'Dữ liệu cần 2 cột với tên và kiểu giá trị là: mssv(kí tự), enable_test(kí tự)',
    DATA_ROOM_WRONG: 'Dữ liệu nhập vào cần gồm 2 cột có tên: room_name(kí tự) và count_computer(số)',
    DATA_TURN_WRONG: 'Dữ liệu nhập vào cần gồm 2 cột có tên: turn(số), time_begin(kí tự)',
    DATA_STUDENT_WRONG: "Dữ liệu nhập vào cần có 4 cột với tên: mssv(kí tự ), name(kí tự), birthday(kí tự), sex(kí tự)",
    DATA_SUBJECT_WRONG: 'Dữ liệu nhập vào cần có 4 cột với tên lần lượt: code_subject(kí tự), name_subject(kí tự), credit(số)',
    DATATYPE_NOT_NUMBER: 'Dữ liệu nhập vào không đúng kiểu.'
}